// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzlowvlvexkkkmpowfrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6bG93dmx2ZXhra2ttcG93ZnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4NTkxODAsImV4cCI6MjA2NzQzNTE4MH0.8W50F97OG8w17D3eN3h9CKyov-3DaqcaedOxarWTAtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});